BuildError: add test related enum variants
They are copied from FromJsonError because it will be removed.

Signed-off-by: Tibor Benke <ihrwein@gmail.com>