TestPairsError: use Strings instead of &str-s in the enum variants
At first I thougth it's a good idea to have only references in the enums,
but it caused a lot of problem. The root cause was that my errors would
certainly outlive their originating place so their references wouldn't be
valid.